### ISSUE TITLE
share location feature on Android

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#1]
we need something as what exist on Windows Phone

Reste à faire : 
- [ ] Quel format pour la latitude/longitude envoyée ?
- [x] Si CAB fermé et re-clique sur un marker (`longClickMarker`) rouvrir la CAB
- [x] Lorsque la CAB s'ouvre, la mettre par dessus la map pour ne pas que ça redimensionne le map fragment. Note que si on a constamment l'app bar dans l'app, ça ne pose pas de souci.

**Comment by EtienneM** [comment]
J'essaye de mettre en place une "Contextual Action Bar" qui apparait : 
- Sur un clique long n'importe où sur la map
- Sur un clique simple sur un marqueur de la map

**Comment by EtienneM** [comment]
Reste à faire : 
- [ ] Quel format pour la latitude/longitude envoyée
- [ ] Lorsque la CAB s'ouvre, la mettre par dessus la map pour ne pas ça redimensionne le map fragment.

**Comment by EtienneM** [comment]
J'ai finalement rajouté l'app bar. Je trouve que le menu sur le côté est trop planqué. Du coup je préfère avoir l'app bar pour pouvoir afficher le hamburger qui permet d'ouvrir ce menu.

**Comment by EtienneM** [comment]
Pour le format des latitude longitude, cf. la [FormatShareLocationMessage](https://github.com/ThePublicBikeGang/EasyBike/blob/master/EasyBike/EasyBike.WinPhone/MainPage.xaml.cs#L1300) de l'application WinPhone.

**Comment by EtienneM** [comment]
Ça a l'air de bien rouler. Je ferme !
