### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#10]
Rendre l'app multilangue en se basant sur la langue du système. Je ne sais pas si c'est déjà le cas pour l'app WinPhone ?

**Comment by MarcMagnin** [comment]
Tout est en anglais pour l'instant. A l'avenir ça serais pas mal mais le multilingue cross platform avec rendu (sur le designer) est assez tendu dans les derniers tests que j'avais fais.

**Comment by EtienneM** [comment]
OK mais par exemple, pour l'appli Android, on a toutes les chaines dans le fichier Strings.xml. Donc les textes ne sont pas partagés entre les plateformes, même sans multilangue. Ou alors c'est ce que j'aurais du faire pour le About ?
