### ISSUE TITLE
Implement Open Source Bike Share API

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#106]
http://opensourcebikeshare.com/

**Comment by EtienneM** [comment]
http://whitebikes.info/command.php?action=map:markers

**Comment by MarcMagnin** [comment]
le repo n'a pas la classe OpenSourceBikeShareContract :D

**Comment by EtienneM** [comment]
T'es sûr ? :D
https://github.com/ThePublicBikeGang/EasyBike/tree/master/EasyBike/EasyBike/Models/Contracts/SK

**Comment by MarcMagnin** [comment]
ah nice, par contre il était manquant dans le csproj ;) j'up

**Comment by MarcMagnin** [comment]
appel moi par skype pour que je t'explique quelques trucs sur les contracts quand t'as le time

**Comment by MarcMagnin** [comment]
c'est intégré ;)

**Comment by EtienneM** [comment]
Hey tu m'as piqué mon issue sur laquelle je jouais ! ^^

**Comment by MarcMagnin** [comment]
haha ! 
Bah du coup comme je compte release un update ce soir, j'ai préféré l'ajouter :p
Mais t'inquiètes y'en a mass d'autre à ajouter ;)
