### ISSUE TITLE
test

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#129]
jhghtf gtf

**Comment by EtienneM** [comment]
Ça c'est une issue ! :D

**Comment by MarcMagnin** [comment]
haha petit con !
j'étais en train de faire une démo au gens de mon équipe à Sky, on utilise
Jira encore pour le tracking ;(

2016-03-17 10:23 GMT+00:00 EtienneM <notifications@github.com>:
