### ISSUE TITLE
Maps cross-platform

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#16]
Savais-tu qu'il y a une classe Xamarin pour avoir une interface commune pour créer des maps : https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/maps/geocode/

Est-ce que ça vaut le coup d'y passer ?

**Comment by EtienneM** [comment]
Pour remplacer le Geocoder : https://www.nuget.org/packages/Xam.Plugin.Geolocator/

**Comment by MarcMagnin** [comment]
Nan on pourra pas faire tout ce dont on a besoin avec la map de xamarin forms :/
