### ISSUE TITLE
Contextual Action Bar : favoris, route et partage

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#17]
La CAB mise en place pour la fonctionnalité #1 peut également être utilisée pour : 
- [x] Ajouter aux favoris
- [x] Demander la route jusqu'à un point
- [ ] ...?

**Comment by EtienneM** [comment]
Pour obtenir la route : https://blog-emildesign.rhcloud.com/?p=822

**Comment by EtienneM** [comment]
Questions : recherche d'itinéraire en mode cycliste ou en mode piéton ?

**Comment by MarcMagnin** [comment]
Stylé !!
mmm pour la recherche si on a le choix les deux peuvent être intéressant ;)
Sinon mode cycliste, ça marchera aussi pour un piéton au cas où et pas l'inverse.

**Comment by MarcMagnin** [comment]
du coup j'ai mis le mode cycliste si l'utilisateur est en vélo, le mode piéton s'il recherche un vélo ;)

**Comment by EtienneM** [comment]
It works
