### ISSUE TITLE
Animations pour la première utilisation

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#18]
À la première utilisation, proposer de télécharger des villes. Si autorisation de l'utilisateur, montrer avec une jolie animation où est le menu de téléchargement des villes.

**Comment by EtienneM** [comment]
En fait, je viens de voir que ça correspondrait dans le MainViewModel à `mainPageLoadedCommand`.

**Comment by MarcMagnin** [comment]
yep carrément :+1:
