### ISSUE TITLE
Navigation view does not work any more

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#20]
Since 6dd773a3eb93e145d05b69190d91919238bfea2a the navigation view does not work anymore...

**Comment by EtienneM** [comment]
L'exception vient du `MainViewModel`qui renvoie une exception ÌnvalidOperationException`avec comme message 
> No CurrentActivity found

La raison est que notre classe helper `ActivityBaseEx` doit hérité de `ActivityBase` avec le  package mvvm-light mais pour la navigation, je l'ai faite hérité de `AppCompatActivity`...

**Comment by MarcMagnin** [comment]
ah merde, je vois. Ca risque de poser problème :+1:

**Comment by MarcMagnin** [comment]
maybe with this solution : https://medium.com/google-developer-experts/how-to-add-toolbar-to-an-activity-which-doesn-t-extend-appcompatactivity-a07c026717b3#.mnl6kbfyb

**Comment by EtienneM** [comment]
Yeah tu roxes !!!!
