### ISSUE TITLE
App crashes with Fatal signal 5 (SIGTRAP), code -6 in tid xxxx (OkHttp Dispatch)

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#22]
When debugging on my Sony Xperia the app crashes often with multiple Fatal signal 5 (SIGTRAP), code -6 in tid xxxx (OkHttp Dispatch)

**Comment by MarcMagnin** [comment]
apparently this happen in debug mode

**Comment by russ-enterapp** [comment]
Hi Marc, I am having a similar issue with Android apps using OpenTok getting the exact same crash.  Can you elaborate on how it was happening in debug mode and how you came to that conclusion?  Did switching to release mode completely solve the issue you were having?

**Comment by MarcMagnin** [comment]
Hi Russ, I've spotted that this problem was not raised in release mode just by testing. It's happening in debug mode randomly. I haven't pushed the investigation further so I can't help you much on that one I'm afraid.

**Comment by russ-enterapp** [comment]
No problem, thank you for the quick reply!


________________________________
