### ISSUE TITLE
finish the about page

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#3]
Liste des choses restantes à faire pour ce ticket :
- [x] lien paypal
- [x] Est-ce possible de partager le texte entre l'appli WinPhone et Android ?
 Oui, j'ai tenté de faire ça au début mais on ne se rend compte de rien dans le designer, c'est la misère.
- [x] rendre les liens (a href) fonctionnel...
- [x] add better font size
- [x] add link for email

**Comment by EtienneM** [comment]
C'est facile à faire, je prends ^^
Je n'ai pas l'adresse PayPal du coupe j'ai pas pu mettre le lien. Tu m'enverras ça ? 
Après j'ai quasiment plus rien à y ajouter.

**Comment by MarcMagnin** [comment]
super! Pour le PayPal faudra que l'on crée une association et que l'on setup un compte dessus car actuellement ça point vers mon compte.
Faudra ptetre update un peu le about pour que ça corresponde plus a la réalité de mainteant.
Surement écrire une section a propos du fait que l'app est dispo sur WP et Android aussi (avec les liens vers les stores)

**Comment by EtienneM** [comment]
Ouaip tout peut aller sur ton compte. Je ferais de toi un homme riche !! ;)

**Comment by EtienneM** [comment]
Liste des choses restantes à faire pour ce ticket :
- [ ] lien paypal
- [ ] rendre les liens (a href) fonctionnel...

Tu vois autre choses ?

**Comment by MarcMagnin** [comment]
le lien paypal est le suivant : https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=marc%2emagnin%40gmail%2ecom&amp;lc=FR&amp;item_name=Marc%20Magnin&amp;currency_code=EUR&amp;bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted

Après c'est pas pour les donations qui tombent que on va devenir riche mais ça méritera d'être posé sur une compte d'une asso histoire de se payer de temps en temps des trucs cools communs.

**Comment by EtienneM** [comment]
Quand je clique sur le lien, ça ne fonctionne pas...
