### ISSUE TITLE
check if we can use the Google API key from MyConfig.json

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#5]

**Comment by EtienneM** [comment]
En suivant ce qui est indiqué ici : https://developer.xamarin.com/guides/android/platform_features/maps_and_location/maps/obtaining_a_google_maps_api_key/
On devrait obtenir une clé d'API pour l'appli en général. Et donc pas une pour toi et une pour moi et une pour cahque personne qui installe l'appli. Est-ce que tu as un compte Google pour l'appli ou on utilise ton compte Google ?

**Comment by EtienneM** [comment]
TL;DR : C'est impossible !

J'ai essayé pas mal de truc en utilisant l'introspection. Mais à priori c'est impossible. Avec le code ci-dessous, on peut modifier la clé de l'API à runtime : 

    MetaDataAttribute attr = Assembly.GetExecutingAssembly().GetCustomAttribute<MetaDataAttribute>();
    if(attr != null) {
      attr.Value = "La clé Google Maps v2";
    }

J'ai utilisé ce post de blog pour y arriver : http://dotnetcodr.com/2014/09/23/reading-assembly-attributes-at-runtime-using-reflection-in-net/

Mais ça ne fonctionne pas car comme indiqué [ici](https://stackoverflow.com/questions/2160476/how-to-set-attributes-values-using-reflection#comment20836616_2161142), les modifications ne persistent pas dans l'objet instantié.
