### ISSUE TITLE
use the last map zoom and location on load 

### ISSUE THREAD

**Issue by MarcMagnin** [ThePublicBikeGang/EasyBike#6]

**Comment by EtienneM** [comment]
Souhaites-tu garder l'ensemble des infos de la position de la caméra ? C'est-à-dire incluant ce qu'ils appellent le [bearing et le tilt](https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition).
Quelle position on utilise par défaut ? GPS ? Pour le debug c'est chez toi mais sinon ?

**Comment by EtienneM** [comment]
> Souhaites-tu garder l'ensemble des infos de la position de la caméra ? C'est-à-dire incluant ce qu'ils appellent le bearing et le tilt.
Non. Juste zoom et position

**Comment by EtienneM** [comment]
>  Quelle position on utilise par défaut ? GPS ? Pour le debug c'est chez toi mais sinon ?

Vue au dessus de l'Europe

**Comment by EtienneM** [comment]
It works
