### ISSUE TITLE
Add a favorite crashes

### ISSUE THREAD

**Issue by EtienneM** [ThePublicBikeGang/EasyBike#81]
Adding a favorite crashed the app on my phone

**Comment by EtienneM** [comment]
C'est étrange... J'ai réessayé après avoir tué brutalement l'app et ça a fonctionné. Puis j'ai quitté l'app en cliquant sur le bouton back, j'ai redémarré l'app et ça a de nouveau planté...

**Comment by MarcMagnin** [comment]
mmm... j'arrive pas a reproduire le truc :/

**Comment by EtienneM** [comment]
NullPointerException L. 821 de MainActivity.cs

**Comment by MarcMagnin** [comment]
nice!

**Comment by MarcMagnin** [comment]
currentMarkerPosition est null ou longclickmarker ?

**Comment by MarcMagnin** [comment]
ok je vois comment le reproduire
